import type * as Phaser from 'phaser'

/**
 * Asset keys and atlas frame names — the single place the strings `scripts/make-atlas.mjs` writes
 * and the strings the game reads are allowed to meet. A frame renamed in the generator without a
 * change here is a silently missing sprite, so both sides point at this file.
 *
 * Loaded by `scenes/Preloader.ts`; regenerate the files themselves with `npm run assets`.
 *
 * **State of the art as of S1** (CHAPAEV-PLAN.md §10): the committed atlas and sound set are the
 * ones carried over from the draughts project, and they are the draughts SHAPES — 1.6:1 ellipses
 * with a crown's headroom reserved above them, tile frames drawn for a checkerboard. S12b
 * regenerates them for this game (round discs, a separate shadow frame, a gloss highlight, the
 * per-branch "floor" sprites of §4) and S10 regenerates the audio for §9's cue list. Everything
 * below is therefore correct about what is ON DISK today, not about what the finished game ships.
 */

export const ATLAS_KEY = 'game'

/**
 * The themed sets. Each one is the board squares, the pieces and the background as a single
 * package — never mixed and matched, so a player cannot assemble a combination nobody looked at.
 *
 * An id is PERMANENT: it is stored in `SaveState.skins` and is also the shop item's id
 * (`src/game/economy.ts`), so renaming one both orphans everyone who bought it and silently
 * un-equips it. `'default'` is the free set every save starts on.
 */
export const SKIN_IDS = ['default', 'emerald', 'sunset', 'frost', 'sand', 'ink', 'crimson', 'plum', 'moss', 'slate'] as const
export type SkinId = (typeof SKIN_IDS)[number]
export const DEFAULT_SKIN: SkinId = 'default'

/** Narrows an arbitrary string — a value out of the save file, which may predate a rename or have
 * been hand-edited — to a skin this build actually ships art for. */
export function isSkinId(value: string): value is SkinId {
  return (SKIN_IDS as readonly string[]).includes(value)
}

/** Texture key of a skin's background. One image per skin, kept out of the atlas because it is a
 * full-screen picture, not a sprite. */
export function backgroundKey(skin: SkinId): string {
  return `bg-${skin}`
}

/** Path under `assets/`, for `Preloader`'s `this.load.image()`. */
export function backgroundPath(skin: SkinId): string {
  return `bg/${skin}.webp`
}

/**
 * The menu's own plate, and the mascot that stands on it.
 *
 * Deliberately NOT members of {@link SKIN_IDS}: that list is indexed by the board sets a player can
 * buy and equip, and these two are neither bought nor equipped. Folding them in would make
 * `equippedSkin()` and the shop's own id space answer for assets no one owns.
 *
 * The menu used to borrow whichever board plate was equipped, which put a picture composed for a
 * board behind a column of buttons. `ART-SOURCES.md` carries the provenance for both.
 */
export const MENU_BACKGROUND_KEY = 'bg-menu'
export const MENU_BACKGROUND_PATH = 'bg/menu.webp'
export const MASCOT_KEY = 'mascot'
export const MASCOT_PATH = 'mascot.webp'
/**
 * The mascot with its eyes shut — the other half of `ui/mascotView.ts`'s idle.
 *
 * A separate FILE rather than a second frame in the atlas, because the mascot is itself a separate
 * file: it is a 425x512 delivery and the atlas is five 64px sprites, so folding it in would make the
 * atlas a different kind of thing. Derived from `mascot.webp` by arithmetic rather than rendered
 * again — `Remotion/src/scripts/chapaev_mascot_blink.py`, and see `ART-SOURCES.md` for why a second
 * render was never an option.
 */
export const MASCOT_BLINK_KEY = 'mascot-blink'
export const MASCOT_BLINK_PATH = 'mascot-blink.webp'

/**
 * The sound set, generated by `scripts/make-audio.mjs` (`npm run audio`) — same "one place the
 * generator's strings and the game's strings meet" rule as the atlas frames. Provenance for every
 * file is in `AUDIO-SOURCES.md`; `scripts/check-bundle.mjs` FAILS the build if a shipped audio
 * file has no row there.
 *
 * Keys and file stems are the same string, so `Preloader` loads them in one loop — which is why
 * the S1 cue names below are still the draughts ones: renaming a key here without regenerating the
 * files would be a build-green, silence-in-game bug. The Chapaev role each cue plays today is in
 * its comment, and S10 (§9) renames key and file together:
 *
 *   move -> shot, capture -> impact (volume/pitch from collision energy), promote -> knockout,
 *   plus a new combo cue with a rising pitch.
 */
export const SFX = {
  /** Every button in the kit, via `ui/theme.ts`'s `setPressSound()`. */
  ui: 'ui',
  /** The flick releasing — one shot fired. */
  move: 'move',
  /** Disc against disc. §9 makes this the game's main sound, scaled by impact energy. */
  capture: 'capture',
  /** A disc leaving the board. */
  promote: 'promote',
  win: 'win',
  lose: 'lose',
} as const

export type SfxKey = (typeof SFX)[keyof typeof SFX]

export const MUSIC_KEY = 'music'

/** Every audio key this game loads, in load order. */
export const AUDIO_KEYS: readonly string[] = [...Object.values(SFX), MUSIC_KEY]

/** Path under `assets/`, for `Preloader`'s `this.load.audio()`. */
export function audioPath(key: string): string {
  return `audio/${key}.ogg`
}


/**
 * The frames a skin replaces: the two board squares and the piece sprites. `light`/`dark` are the
 * two SIDES, named for the one thing that is identical in every skin — one side is always the
 * light one, the other always the dark one.
 *
 * `king*` are the draughts crowned pieces. Chapaev has no promotion, but it does have §4's branch
 * of arms: a heavier disc with a "floor" on top (the artillery's gun, the tank's turret). S12b
 * repoints these two slots at that, which is why they are kept rather than deleted — the atlas,
 * the generator and the naming convention all already handle "a second sprite per side".
 */
/**
 * Named frames in the atlas.
 *
 * There are fourteen, and there used to be thirty-five: `skinFrames()` and the 24 per-skin piece and
 * tile frames it named went with S12b, along with the draughts cell highlights and mascot. The
 * discs are generated at runtime instead (`board/discTextures.ts`) because a disc is one sprite per
 * piece set per branch mark per side, and baking that grows multiplicatively with every set added.
 */
export const ATLAS_FRAMES = {
  /** The coin. **The shop's prices and the top bar's balance both point here** — a price marked
   * with a different symbol than the balance reads as a different currency. */
  coin: 'icon-coin',
  /**
   * The three mute states, DRAWN rather than typed.
   *
   * They were the emoji U+1F507 / U+1F508 / U+1F50A set in a `Text`, until a phone came back with
   * both settings buttons showing tofu boxes: a control whose meaning IS a system glyph stops
   * meaning anything on a device that does not own it, and nothing then said whether sound or music
   * was muted. The coin above had been the counter-example in this same file all along.
   *
   * Three, not two, for the reason the glyphs had three: a speaker with no waves reads as "quiet"
   * rather than "off", so the cross is what says off.
   */
  soundOn: 'icon-sound-on',
  soundLow: 'icon-sound-low',
  soundOff: 'icon-sound-off',
  /**
   * The chrome: three navigation tabs and the settings gear, drawn for the same reason the speakers
   * are. These carry their own word underneath (or, for the gear, sit alone in the top bar's only
   * button), so a missing glyph cost less here than it did on the mute buttons — it still put four
   * tofu boxes on the two bars a player looks at most.
   *
   * **White in the atlas, tinted at the call site.** A sprite takes a tint and an emoji does not,
   * so a nav tab's icon now goes gold with its label instead of staying whatever colour the
   * device's emoji font happened to make it.
   */
  home: 'icon-home',
  shop: 'icon-shop',
  modes: 'icon-modes',
  gear: 'icon-gear',
  /** The two consumables, on their HUD buttons — a mark beside the price it costs. */
  retake: 'icon-retake',
  power: 'icon-power',
  sparkParticle: 'particle-spark',
  shardParticle: 'particle-shard',
  rimStrip: 'rim-strip',
  rimCorner: 'rim-corner',
} as const

/**
 * ## The piece-frame geometry is gone, and that is S12b's real conclusion
 *
 * `PIECE_FRAME_SIZE`, `PIECE_DISC_FRACTION` and `pieceAnchorY()` all existed to reconcile the game
 * with an atlas frame that reserved headroom above the disc for a CROWN — draughts geometry, in a
 * game with no kings and no isometry (CHAPAEV-PLAN.md §2). Nothing read them.
 *
 * The note they carried was that the shadow must become its own frame with its own offset, because
 * a shadow baked into the disc flies along with a struck piece. That is done, and it is done in
 * `board/discTextures.ts` rather than here: the shadow is a separate texture the view positions at
 * its own offset, which is exactly what §2 asked for and what let a disc tumbling off the rim leave
 * its shadow behind on the surface.
 */

